apiVersion: v1
kind: Service
metadata:
  name: jawsome-frontend-service
spec:
  selector:
    app: jawsome-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
